excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length: 200

disabled_rules: # rule identifiers turned on by default to exclude from running
  - unused_closure_parameter
